---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.3.0

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:
  cluster-base-configure:
    parameters:
      cluster:
        description: cluster name to use for configuration
        type: string
        default: ""
    steps:
      - run:
          name: pull kubeconfig
          shell: secrethub run -- /bin/sh -eo pipefail
          command: |
            mkdir ~/.kube
            SECRETHUB_VAR_ENV=<< parameters.cluster >> secrethub inject -i tpl/kubeconfig.tpl -o ~/.kube/config
      - run:
          name: deploy external-dns
          command: bash tpl/deploy_external_dns.sh sandbox
      - run:
          name: deploy cluster-autoscaler
          command: bash tpl/deploy_cluster_autoscaler.sh << parameters.cluster >> $(cat << parameters.cluster >>.auto.tfvars.json | jq -r '.aws_region')
      - run:
          name: deploy metrics-apis
          command: kubectl apply -f metrics-apis --recursive
      - run:
          name: deploy containter-insights
          command: bash tpl/deploy_cloud_watch.sh << parameters.cluster >> $(cat << parameters.cluster >>.auto.tfvars.json | jq -r '.aws_region')
      - run:
          name: validate pod status for cluster-autoscaler and metrics api deployments
          command: |
            secrethub inject -i tpl/cluster_deployments_test.sh.tpl -o cluster_deployments_test.sh
            bash cluster_deployments_test.sh << parameters.cluster >>
      - run:
          name: cis benchmarks
          command: bash tpl/kube_bench.sh

workflows:
  version: 2

  poc-platform-eks-pipeline:
    jobs:
      - terraform/plan:
          name: sandbox-change-plan
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          filters: *on-push-master

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: sandbox-change-apply
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
                  secrethub inject -i tpl/nonprod.test.sh.tpl -o nonprod.test.sh
          after-terraform:
            - run:
                name: test sandbox account changes
                environment:
                  TEST_ENV: sandbox
                  KUBECONFIG: kubeconfig
                command: |
                  secrethub run -- bash nonprod.test.sh sandbox
                  secrethub run -- bash tpl/write_cluster_credentials.sh sandbox
            # - cluster-base-configure:
            #     cluster: sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-master

      # git tag - release pipeline
      - terraform/plan:
          name: preview-change-plan
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
          filters: *on-tag-master

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-master

      - terraform/apply:
          name: preview-change-apply
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
                  secrethub inject -i tpl/nonprod.test.sh.tpl -o nonprod.test.sh
          after-terraform:
            - run:
                name: test preview account changes
                environment:
                  TEST_ENV: preview
                command: |
                  secrethub run -- bash nonprod.test.sh preview
                  secrethub run -- bash tpl/write_cluster_credentials.sh preview
            - cluster-base-configure:
                cluster: preview
          requires:
            - approve-preview-changes
          filters: *on-tag-master

  poc-platform-eks-teardown:
    jobs:
      - teardown-clusters:
          type: approval
          filters: *on-push-master

      - approve-teardown-sandbox:
          type: approval
          requires:
            - teardown-clusters
          filters: *on-push-master
      
      - approve-teardown-preview:
          type: approval
          requires:
            - teardown-clusters
          filters: *on-push-master

      - terraform/destroy:
          name: sandbox-destroy
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          requires:
            - approve-teardown-sandbox
          filters: *on-push-master

      - terraform/destroy:
          name: preview-destroy
          context: dps-va-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
          requires:
            - approve-teardown-preview
          filters: *on-push-master
